pipeline {
  environment {
        DOCKERHUB_CREDENTIALS = credentials('sageiyke-dockerhub')
    }
    agent any
    stages {
        stage('Connect to Github') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/iyketheintrovert/git_exercise']])
            }
        }
        stage('Build Docker Image') {
            steps {
              script {
                sh 'docker build -t dockerfile .'
              }
            }
        }
        stage('Run Docker Container') {
            steps {
              script {
                sh 'docker run -itd --name nginx -p 8081:80 dockerfile'
              }
            }
        }
        stage('Login to DockerHub') {
            steps {
              script {
                  sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                }
            }
        }
        stage('Tag Image') {
            steps {
              script {
                  sh 'docker tag dockerfile sageiyke/dockerfile:latest'
              }
            }
        }
        stage('Push to DockerHub') {
            steps {
              script {
                  sh 'docker push sageiyke/dockerfile:latest'
              }
            }
        }
    }
    post {
      always {
        sh 'docker logout'
      }
    }
}
